### ISSUE TITLE
isPartOf Mapping not used in functional_class.py

### ISSUE THREAD

**Issue by cthoyt** [pathwayforte/pathway-forte#11]
https://github.com/pathwayforte/pathway-forte/blob/6acfcbb3b09d3ee7064f9365da5160d81c53e94a/src/pathway_forte/pathway_enrichment/functional_class.py#L371

Why is this here if it doesn't get used?

**Comment by ddomingof** [comment]
We thought to use these mappings too but we decided to go only for equivalent pathways

**Comment by ddomingof** [comment]
I make a comment there in case anybody wants to use them in the future
I think it is interesting to leave it...
