### ISSUE TITLE
y_test is never used in survival analysis

### ISSUE THREAD

**Issue by cthoyt** [pathwayforte/pathway-forte#12]
https://github.com/pathwayforte/pathway-forte/blob/03db23a9b910ae1ebec90e6d8f3bacd94bb43f2a/src/pathway_forte/prediction/survival.py#L156

**Comment by cthoyt** [comment]
oh i see its because there's more stuff in the data structure and it gets unpacked later when making the evaluation. It still looks a bit messy - there's room for refactoring

**Comment by ddomingof** [comment]
Yep!
